### PR TITLE
Dao feature updated ofa

### PR DESCRIPTION
**Pull request by daonguyen81**
Can any of you review the ofa crawler?

### CODE REVIEW

**Review by MikeJLeon — CHANGES_REQUESTED** [review]
Code error when on last one. Please review code and see what is wrong, or tell me if I am missing something. Thank you Dao.

```
1 remain
Connecting to https://localendar.com/event?DAM=PublishedEvent&m=333899&event_id=1422&calendar_id=333899&more_info=N&export_date=Mar%2002,%202019&category=8; success
Scraping finished https://localendar.com/event?DAM=PublishedEvent&m=333899&event_id=1422&calendar_id=333899&more_info=N&export_date=Mar%2002,%202019&category=8; success
0 remain
Scrapping page: 2...
35 Links found
Error gathering URL data, Message: unknown error: Element <div class=" lc-tdn cal_333899 m-titlepad cat_8 iela " onclick="javascript:PublicEventDetail(333899,333899,1428,&quot;N&quot;,&quot;Jan 27, 2019&quot;,8)" style="white-space:pre-wrap;cursor: pointer;color:#000000;">...</div> is not clickable at point (72, 141). Other element would receive the click: <div class="blockUI blockOverlay" style="z-index: 1000; border: none; margin: 0px; padding: 0px; width: 100%; height: 100%; top: 0px; left: 0px; background-color: rgb(51, 51, 51); opacity: 0.577185; cursor: wait; position: absolute;"></div>
  (Session info: headless chrome=71.0.3578.98)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.17134 x86_64)

Closing browser scraper; 2019-02-19 21:24:21.740654
```

**Review by MikeJLeon — CHANGES_REQUESTED** [review]
Also please refer to this nomenclature for logging and try and make changes.

Link - https://github.com/ActoKids/AD440_W19_CloudPracticum/wiki/Logging-style-guide-for-crawling-and-scraping

Code sample below.
```
Starting browser crawler; 2019-02-19 21:29:40.822658
Opening https://www.eventbrite.com/d/wa--seattle/disability/?page=1; success
Found link https://www.eventbrite.com/e/help-im-invisible-invisible-disabilities-in-the-workplace-tickets-56439603373?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/p4p-presents-models-of-disability-how-do-we-ensure-everyone-belongs-tickets-55034038290?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/lets-talk-about-inspiration-porn-tickets-55596210763?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/blackafrican-american-community-social-2019-tickets-48468415335?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/529-college-savings-plans-for-grandparents-tickets-56454943255?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/bridging-family-culture-graduate-school-tickets-55541710752?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/sarcoma-patient-and-caregiver-education-program-for-patients-and-their-loved-ones-tickets-54154265867?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/all-about-able-tickets-54895925190?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/vshsl-community-planning-session-adaptive-devices-training-and-counseling-tickets-54894383579?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/2019-transition-workshop-substance-abuse-in-vulnerable-populations-tickets-53019363343?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/politics-policy-and-privacy-in-the-data-economy-tickets-56380199695?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/two-day-soar-training-tickets-55011123752?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/promoting-participation-physical-activity-fair-tickets-54559123808?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/peers-of-king-county-mardi-gras-celebration-tickets-56958664900?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/understanding-anti-discrimination-anti-harassment-as-it-pertains-to-your-role-as-a-manager-tickets-54935848602?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/cross-agency-system-training-cast-2019-registration-44035889531?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/updates-in-bladder-and-and-urinary-tract-cancers-for-patients-and-their-loved-ones-tickets-53758234326?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/naiomt-c-616-cervical-spine-ii-seattlerenton2019-tickets-50714484388?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/naiomt-c-613-thoracic-spine-seattlerenton2019-tickets-50714714075?aff=ebdssbdestsearch
Found link https://www.eventbrite.com/e/naiomt-c-611-lumbopelvic-spine-i-seattlerenton2019-tickets-50810598869?aff=ebdssbdestsearch

```

**Comment by mrvirus9898** [comment]
Hey Dao, whats up with the eventbrite work? Just need Outdoors for all from you bro.

**Review by MikeJLeon — APPROVED** [review]

**Review by mrvirus9898 — COMMENTED** [review]
Approved

**Review by mrvirus9898 — APPROVED** [review]

**Pull request merged**
