### PR TITLE
Mike feature/awscompatible

### PR DESCRIPTION
**Pull request by MikeJLeon**
This pull requests contains the OFAScraper and SSScraper as it appears on the EC2. code writes to dynamo and prints to a log file which is uploaded to cloudwatch if it appears on the EC2.

### CODE REVIEW

**Comment by MikeJLeon** [comment]
To Test - Requires a AWS credential in your environmental variables which are applicable for our class AWS. This is for dynamo. If dynamo is inactive then it should simply create a log file.

To Test ON AWS - go to our lambda functions 
Launch -
ad440-w19-lambda-crawler-launchec2
Check if ec2 is running,
Wait a bit and see if logs appeared on Cloudwatch under crawlerlogs

**Review by daonguyen81 — APPROVED** [review]
It worked great Mike, the Lambda trigger the EC2 to run both the crawler scripts, the log output worked as expected. The EC2 stopped after running the scripts as expected. I approve this PR.

**Review by TyReed12 — APPROVED** [review]
Everything worked as expected. Great work Mike!

**Comment by daonguyen81** [comment]
I ran the test again several times and I found an error in the OFA scraper.

**Pull request merged**
