### PR TITLE
Create Lambda Function

### PR DESCRIPTION
**Pull request by rberry206**
The lambda function for the Google Calendar crawler. The full package required to run this code can be seen on AWS Lambda. The file structure is too big to put on GitHub.

### CODE REVIEW

**Review by daonguyen81 — APPROVED** [review]
Just ran a test on your googleLambda,  it worked great! Logs output and data look great, didn't find any error. Good job Ryan!

**Comment by mrvirus9898** [comment]
Which lambda is the current package loaded to? Also, is the lambda_function too large to post? If not, could it be posted sense that's the part where the magic happens.

**Comment by rberry206** [comment]
Currently loaded to ad440-w19-lambda-crawler-googlecrawler. And yes, it's too large to post and does not work outside of our AWS account (it's using all local calls, no external variable calls).

**Comment by MikeJLeon** [comment]
I've helped ryan build this. The crawler runs as expected and is writing to Dynamo. Tested by running the lambda itself and checking the entries on Dynamo to see if everything ran fine. 

Some warnings appear such as the following
```
[WARNING]	2019-03-06T23:28:58.357Z	9c43f16f-24b8-47dc-ae52-878637d63158	file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/var/task/googleapiclient/discovery_cache/__init__.py", line 36, in autodetect
    from google.appengine.api import memcache
ModuleNotFoundError: No module named 'google.appengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/googleapiclient/discovery_cache/file_cache.py", line 33, in <module>
    from oauth2client.contrib.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.contrib.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/googleapiclient/discovery_cache/file_cache.py", line 37, in <module>
    from oauth2client.locked_file import LockedFile
ModuleNotFoundError: No module named 'oauth2client.locked_file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/var/task/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-authStarting GoogleCalendar crawler;  2019-03-06 23:28:59.115199
Opening calendars: Success
Closing GoogleCalendar crawler;  2019-03-06 23:29:04.396019
END RequestId: 9c43f16f-24b8-47dc-ae52-878637d63158
REPORT RequestId: 9c43f16f-24b8-47dc-ae52-878637d63158	Duration: 6382.98 ms	Billed Duration: 6400 ms 	Memory Size: 128 MB	Max Memory Used: 94 MB	
```
However the code still runs and writes to Dynamo as expected. I will approve this, we can fix these errors in time.

**Review by MikeJLeon — APPROVED** [review]
Approved

**Pull request merged**
